import Foundation
import SQLite3

/// Builds `db/populated.db` and `db/schema.sql` by running the shipping storage code.
///
/// The four `CREATE TABLE` statements come from the real `HistoryStore`,
/// `DictionaryStore`, `PolishStore` and `NotesStore` initialisers, constructed in the
/// order `AppDelegate` constructs them, against the real `DatabaseManager`. That is the
/// part the Rust port has to match exactly, and it is genuinely executed here.
///
/// Rows are inserted with literal SQL rather than through `addEntry`/`addNote`, because
/// those stamp `UUID()` and `Date()` into every row and the fixtures have to be
/// byte-stable across runs. The column lists below mirror each store's `INSERT`
/// verbatim, so the shapes still come from the reference.
enum FixtureDatabase {
    /// 2025-01-01T00:00:00Z. Fixed so `REAL` timestamp columns are reproducible.
    static let epoch: Double = 1_735_689_600

    struct Built {
        let databaseURL: URL
        let schemaSQL: String
        let vocabularyPhrases: [String]
        let replacements: [String: String]
        let snippets: [String: String]
        let rowCounts: [String: Int]
    }

    static func build(sandboxHome: URL) throws -> Built {
        let dbManager = DatabaseManager()
        guard dbManager.db != nil else {
            throw FixtureError("DatabaseManager failed to open a database under \(sandboxHome.path)")
        }

        // Construction order matches AppDelegate: HistoryStore, DictionaryStore,
        // PolishStore, NotesStore. Each initialiser issues its own CREATE TABLE.
        _ = HistoryStore(dbManager: dbManager)
        let dictionaryStore = DictionaryStore(dbManager: dbManager)
        _ = PolishStore(dbManager: dbManager)
        _ = NotesStore(dbManager: dbManager)

        dbManager.transaction {
            for statement in transcriptRows() { dbManager.exec(statement) }
            for statement in dictionaryRows() { dbManager.exec(statement) }
            for statement in polishRows() { dbManager.exec(statement) }
            for statement in noteRows() { dbManager.exec(statement) }
        }

        // Read back through the real store so the dictionary fixtures exercise the
        // shipping queries — the LIMIT 50, the ORDER BY frequency_used DESC, and the
        // is_deleted / is_snippet filters — rather than a reimplementation of them.
        let vocabulary = dictionaryStore.getVocabularyPhrases()
        let replacements = dictionaryStore.getReplacements()
        let snippets = dictionaryStore.getSnippets()

        let schema = try dumpSchema(dbManager.db)
        var counts: [String: Int] = [:]
        for table in ["transcripts", "dictionary", "polish", "notes"] {
            counts[table] = try rowCount(dbManager.db, table: table)
        }

        // Closing checkpoints and removes the -wal file that `PRAGMA journal_mode=WAL`
        // created, leaving a single self-contained database to commit.
        dbManager.close()

        let databaseURL = sandboxHome
            .appendingPathComponent("Library/Application Support/WisprLightning/lightning.db")
        guard FileManager.default.fileExists(atPath: databaseURL.path) else {
            throw FixtureError("expected a database at \(databaseURL.path)")
        }

        return Built(
            databaseURL: databaseURL,
            schemaSQL: schema,
            vocabularyPhrases: vocabulary,
            replacements: replacements,
            snippets: snippets,
            rowCounts: counts
        )
    }

    // MARK: - Schema dump

    private static func dumpSchema(_ db: OpaquePointer?) throws -> String {
        let sql = "SELECT type, name, sql FROM sqlite_master ORDER BY name;"
        var stmt: OpaquePointer?
        guard sqlite3_prepare_v2(db, sql, -1, &stmt, nil) == SQLITE_OK else {
            throw FixtureError("could not read sqlite_master: \(errorMessage(db))")
        }
        defer { sqlite3_finalize(stmt) }

        var lines: [String] = [
            "-- Generated by `swift run fixturegen` from tools/fixturegen. Do not hand-edit.",
            "-- Verbatim `sqlite_master.sql` after HistoryStore, DictionaryStore, PolishStore",
            "-- and NotesStore have each run their CREATE TABLE, ordered by object name.",
            ""
        ]
        while sqlite3_step(stmt) == SQLITE_ROW {
            let type = text(stmt, 0) ?? ""
            let name = text(stmt, 1) ?? ""
            if let ddl = text(stmt, 2) {
                lines.append("\(ddl);")
            } else {
                // Implicit indexes — one per `TEXT PRIMARY KEY` and one for
                // `UNIQUE(phrase, team_dictionary_id)`. They have no DDL of their own but
                // are still part of the schema the port has to end up with.
                lines.append("-- \(type) \(name): created implicitly by a PRIMARY KEY or UNIQUE constraint, no DDL")
            }
            lines.append("")
        }
        return lines.joined(separator: "\n")
    }

    private static func rowCount(_ db: OpaquePointer?, table: String) throws -> Int {
        var stmt: OpaquePointer?
        guard sqlite3_prepare_v2(db, "SELECT COUNT(*) FROM \(table);", -1, &stmt, nil) == SQLITE_OK else {
            throw FixtureError("could not count \(table): \(errorMessage(db))")
        }
        defer { sqlite3_finalize(stmt) }
        guard sqlite3_step(stmt) == SQLITE_ROW else {
            throw FixtureError("no count row for \(table)")
        }
        return Int(sqlite3_column_int64(stmt, 0))
    }

    private static func text(_ stmt: OpaquePointer?, _ index: Int32) -> String? {
        guard let c = sqlite3_column_text(stmt, index) else { return nil }
        return String(cString: c)
    }

    private static func errorMessage(_ db: OpaquePointer?) -> String {
        guard let c = sqlite3_errmsg(db) else { return "unknown error" }
        return String(cString: c)
    }

    // MARK: - Deterministic rows

    private static func quote(_ value: String) -> String {
        "'" + value.replacingOccurrences(of: "'", with: "''") + "'"
    }

    private static func quote(_ value: String?) -> String {
        value.map(quote) ?? "NULL"
    }

    /// Columns mirror `HistoryStore.addEntry`.
    private static func transcriptRows() -> [String] {
        struct Row {
            let id: String
            let asr: String?
            let formatted: String?
            let offset: Double
            let appName: String
            let bundleId: String
            let duration: Double
            let words: Int
            let language: String
        }
        let rows = [
            Row(id: "0A000001-0000-4000-8000-000000000001",
                asr: "hey can you send me the report",
                formatted: "Hey, can you send me the report?",
                offset: 0, appName: "Slack", bundleId: "com.tinyspeck.slackmacgap",
                duration: 2.4, words: 7, language: "en"),
            // formatted_text NULL: what the transcribe-only pipeline stores.
            Row(id: "0A000002-0000-4000-8000-000000000002",
                asr: "raw only no formatting was requested",
                formatted: nil,
                offset: 63.5, appName: "Terminal", bundleId: "com.apple.Terminal",
                duration: 3.04, words: 6, language: "en"),
            // asr_text NULL, and non-ASCII: pins UTF-8 round-tripping through SQLite.
            Row(id: "0A000003-0000-4000-8000-000000000003",
                asr: nil,
                formatted: "Café au lait, s'il vous plaît — 90 % sûr.",
                offset: 3600, appName: "Mail", bundleId: "com.apple.mail",
                duration: 4.16, words: 8, language: "fr"),
            Row(id: "0A000004-0000-4000-8000-000000000004",
                asr: "quote 'single' and \"double\" quotes",
                formatted: "Quote 'single' and \"double\" quotes.",
                offset: 86_400, appName: "Xcode", bundleId: "com.apple.dt.Xcode",
                duration: 40.04, words: 5, language: "en")
        ]
        return rows.map { row in
            """
            INSERT OR REPLACE INTO transcripts \
            (id, asr_text, formatted_text, timestamp, app_name, app_bundle_id, duration, num_words, language) \
            VALUES (\(quote(row.id)), \(quote(row.asr)), \(quote(row.formatted)), \(epoch + row.offset), \
            \(quote(row.appName)), \(quote(row.bundleId)), \(row.duration), \(row.words), \(quote(row.language)));
            """
        }
    }

    /// Columns mirror `DictionaryStore.addEntry`, plus the columns that method leaves
    /// at their defaults (`is_deleted`, `frequency_used`) where a fixture needs them set.
    ///
    /// `frequency_used` is unique per row on purpose: `getVocabularyPhrases` orders by it
    /// descending with no tiebreaker, so equal values would make the fixture depend on
    /// SQLite's scan order.
    private static func dictionaryRows() -> [String] {
        struct Row {
            let id: String
            let phrase: String
            let replacement: String?
            let isSnippet: Bool
            let manualEntry: Bool
            let source: String
            let frequency: Int
            let isDeleted: Bool
        }
        var rows: [Row] = []
        var nextId = 1
        func id() -> String {
            defer { nextId += 1 }
            return String(format: "0D%06X-0000-4000-8000-%012X", nextId, nextId)
        }

        // Highest frequency of all, and soft-deleted: it must NOT appear in any output.
        rows.append(Row(id: id(), phrase: "Deleted Vocabulary", replacement: nil,
                        isSnippet: false, manualEntry: true, source: "manual",
                        frequency: 500, isDeleted: true))
        // A replacement entry ranked inside the top 50, proving replacement-bearing rows
        // are also returned as vocabulary.
        rows.append(Row(id: id(), phrase: "gpt", replacement: "GPT",
                        isSnippet: false, manualEntry: true, source: "manual",
                        frequency: 499, isDeleted: false))
        // 55 plain vocabulary terms against a LIMIT of 50, so the cut-off is observable.
        for term in 1...55 {
            rows.append(Row(id: id(), phrase: String(format: "Vocab Term %02d", term),
                            replacement: nil, isSnippet: false, manualEntry: false,
                            source: term % 2 == 0 ? "user_edits" : "csv_import",
                            frequency: 499 - term, isDeleted: false))
        }
        rows.append(Row(id: id(), phrase: "api", replacement: "API",
                        isSnippet: false, manualEntry: true, source: "manual",
                        frequency: 443, isDeleted: false))
        rows.append(Row(id: id(), phrase: "cafe", replacement: "café",
                        isSnippet: false, manualEntry: true, source: "manual",
                        frequency: 442, isDeleted: false))
        rows.append(Row(id: id(), phrase: "wispr flow", replacement: "Wispr Flow",
                        isSnippet: false, manualEntry: true, source: "default",
                        frequency: 441, isDeleted: false))
        rows.append(Row(id: id(), phrase: "my email", replacement: "mike@example.com",
                        isSnippet: true, manualEntry: true, source: "manual",
                        frequency: 440, isDeleted: false))
        // Multi-line snippet: the value must survive JSON and SQLite unchanged.
        rows.append(Row(id: id(), phrase: "sig", replacement: "Mike Chen\nWispr Lightning\n+1 555 0100",
                        isSnippet: true, manualEntry: true, source: "manual",
                        frequency: 439, isDeleted: false))
        rows.append(Row(id: id(), phrase: "addr", replacement: "1 Infinite Loop, Cupertino, CA",
                        isSnippet: true, manualEntry: true, source: "csv_import",
                        frequency: 438, isDeleted: false))
        rows.append(Row(id: id(), phrase: "Deleted Snippet", replacement: "never sent",
                        isSnippet: true, manualEntry: true, source: "manual",
                        frequency: 437, isDeleted: true))

        return rows.enumerated().map { index, row in
            let created = epoch + Double(index)
            return """
            INSERT OR IGNORE INTO dictionary \
            (id, phrase, replacement, is_snippet, manual_entry, source, frequency_used, created_at, modified_at, is_deleted) \
            VALUES (\(quote(row.id)), \(quote(row.phrase)), \(quote(row.replacement)), \
            \(row.isSnippet ? 1 : 0), \(row.manualEntry ? 1 : 0), \(quote(row.source)), \
            \(row.frequency), \(created), \(created), \(row.isDeleted ? 1 : 0));
            """
        }
    }

    /// Columns mirror `PolishStore.saveResult`, which hard-codes `status = 'completed'`.
    private static func polishRows() -> [String] {
        struct Row {
            let id: String
            let initial: String
            let polished: String
            let initialWords: Int
            let polishedWords: Int
            let app: String
            let processingTime: Double
            let instruction: String
            let offset: Double
        }
        let rows = [
            Row(id: "0B000001-0000-4000-8000-000000000001",
                initial: "so basically what i wanted to say is that the thing is broken",
                polished: "The thing is broken.",
                initialWords: 13, polishedWords: 4, app: "Slack",
                processingTime: 1.284,
                instruction: "Make more concise. Reword for clarity",
                offset: 10),
            Row(id: "0B000002-0000-4000-8000-000000000002",
                initial: "please review the attached document and let me know",
                polished: "Please review the attached document and let me know your thoughts.",
                initialWords: 8, polishedWords: 10, app: "Mail",
                processingTime: 0.912,
                instruction: "Maintain your tone",
                offset: 20),
            Row(id: "0B000003-0000-4000-8000-000000000003",
                initial: "résumé updated — take a look",
                polished: "My résumé is updated; please take a look.",
                initialWords: 5, polishedWords: 8, app: "",
                processingTime: 2.5,
                instruction: "Add structure for readability. Clarify main point",
                offset: 30)
        ]
        return rows.map { row in
            let ts = epoch + row.offset
            return """
            INSERT OR REPLACE INTO polish \
            (id, initial_text, polished_text, initial_word_count, polished_word_count, app, processing_time, status, instruction, created_at, updated_at) \
            VALUES (\(quote(row.id)), \(quote(row.initial)), \(quote(row.polished)), \
            \(row.initialWords), \(row.polishedWords), \(quote(row.app)), \(row.processingTime), \
            'completed', \(quote(row.instruction)), \(ts), \(ts));
            """
        }
    }

    /// Columns mirror `NotesStore.addNote`. Row 3 is longer than 200 characters so the
    /// `content_preview` truncation is exercised; the text is pure ASCII because
    /// `String.prefix(200)` counts grapheme clusters, and the port should not have to
    /// guess which unit a fixture meant.
    private static func noteRows() -> [String] {
        let longContent = String(repeating: "The quick brown fox jumps over the lazy dog. ", count: 8)
        struct Row {
            let id: String
            let title: String
            let content: String
            let offset: Double
            let isDeleted: Bool
            let finalized: Bool
        }
        let rows = [
            Row(id: "0C000001-0000-4000-8000-000000000001",
                title: "Untitled", content: "", offset: 0, isDeleted: false, finalized: false),
            Row(id: "0C000002-0000-4000-8000-000000000002",
                title: "Standup — 2025-01-01",
                content: "Shipped the packetizer. Next: ascii85 vectors.",
                offset: 120, isDeleted: false, finalized: true),
            Row(id: "0C000003-0000-4000-8000-000000000003",
                title: "Long note", content: longContent,
                offset: 240, isDeleted: false, finalized: false),
            Row(id: "0C000004-0000-4000-8000-000000000004",
                title: "Trashed", content: "Should not appear in getNotes().",
                offset: 360, isDeleted: true, finalized: false)
        ]
        return rows.map { row in
            let ts = epoch + row.offset
            let preview = String(row.content.prefix(200))
            return """
            INSERT INTO notes (id, title, content_preview, content, created_at, modified_at, is_deleted, finalized) \
            VALUES (\(quote(row.id)), \(quote(row.title)), \(quote(preview)), \(quote(row.content)), \
            \(ts), \(ts), \(row.isDeleted ? 1 : 0), \(row.finalized ? 1 : 0));
            """
        }
    }
}
