//! Golden-fixture parity tests against the shipping Swift implementation.
//!
//! Generated by `tools/fixturegen` (`swift run fixturegen`). These are the
//! tests that prove the port did not quietly change behaviour: everything
//! else checks that the Rust code does what the Rust author intended, while
//! these check that it does what the *original* did.

use std::path::{Path, PathBuf};

use wl_core::consts::{CHUNK_BYTES, CHUNK_SAMPLES};

fn fixtures() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../tests/fixtures")
        .canonicalize()
        .expect("tests/fixtures is missing; run `swift run fixturegen`")
}

fn read_json<T: serde::de::DeserializeOwned>(rel: &str) -> T {
    let path = fixtures().join(rel);
    let bytes = std::fs::read(&path).unwrap_or_else(|e| panic!("missing {rel}: {e}"));
    serde_json::from_slice(&bytes).unwrap_or_else(|e| panic!("{rel} is not valid JSON: {e}"))
}

// ---------------------------------------------------------------------------
// Audio framing and RMS
// ---------------------------------------------------------------------------

#[derive(serde::Deserialize)]
struct PacketManifest {
    packet_count: usize,
    samples_per_packet: usize,
    bytes_per_packet: usize,
    sample_rate: u32,
    channels: u16,
    chunk_duration_ms: u32,
    pcm_file: String,
    packets: Vec<PacketVolume>,
}

#[derive(serde::Deserialize)]
struct PacketVolume {
    index: usize,
    volume: f64,
}

#[test]
fn protocol_constants_match_the_reference_implementation() {
    let m: PacketManifest = read_json("pcm/packets.json");
    assert_eq!(m.sample_rate, wl_core::consts::SAMPLE_RATE);
    assert_eq!(m.channels, wl_core::consts::CHANNELS);
    assert_eq!(m.chunk_duration_ms, wl_core::consts::CHUNK_DURATION_MS);
    assert_eq!(m.samples_per_packet, CHUNK_SAMPLES);
    assert_eq!(m.bytes_per_packet, CHUNK_BYTES);
}

#[test]
fn packet_volumes_match_the_reference_rms_for_every_packet() {
    let m: PacketManifest = read_json("pcm/packets.json");
    let pcm = std::fs::read(fixtures().join(&m.pcm_file)).expect("missing reference PCM");
    assert_eq!(pcm.len(), m.packet_count * CHUNK_BYTES);

    let packets: Vec<Vec<i16>> = pcm
        .chunks_exact(CHUNK_BYTES)
        .map(|c| {
            c.chunks_exact(2)
                .map(|s| i16::from_le_bytes([s[0], s[1]]))
                .collect()
        })
        .collect();
    assert_eq!(packets.len(), m.packets.len());

    let mut mismatches = Vec::new();
    for expected in &m.packets {
        let actual = wl_core::audio::packet_volume(&packets[expected.index]);
        if actual != expected.volume {
            mismatches.push(format!(
                "packet {}: expected {}, got {actual}",
                expected.index, expected.volume
            ));
        }
    }
    assert!(
        mismatches.is_empty(),
        "{} of {} packet volumes diverged:\n{}",
        mismatches.len(),
        m.packets.len(),
        mismatches
            .iter()
            .take(10)
            .cloned()
            .collect::<Vec<_>>()
            .join("\n")
    );

    // Guard against a fixture that is accidentally all silence, which would
    // make the comparison above vacuous.
    let distinct: std::collections::BTreeSet<_> =
        m.packets.iter().map(|p| p.volume.to_bits()).collect();
    assert!(
        distinct.len() > 100,
        "the reference audio is too uniform to be a meaningful check ({} distinct volumes)",
        distinct.len()
    );
}

#[test]
fn repacketizing_the_reference_pcm_reproduces_it_exactly() {
    let m: PacketManifest = read_json("pcm/packets.json");
    let pcm = std::fs::read(fixtures().join(&m.pcm_file)).unwrap();
    let samples: Vec<i16> = pcm
        .chunks_exact(2)
        .map(|s| i16::from_le_bytes([s[0], s[1]]))
        .collect();

    // Feed it through in deliberately awkward buffer sizes, none of which
    // divide 640 — this is what a real audio callback looks like.
    let mut packetizer = wl_core::audio::Packetizer::new();
    let mut out: Vec<u8> = Vec::with_capacity(pcm.len());
    let mut offset = 0;
    for size in [1021usize, 37, 4096, 3, 512].into_iter().cycle() {
        if offset >= samples.len() {
            break;
        }
        let end = (offset + size).min(samples.len());
        packetizer.push(&samples[offset..end], |p| {
            out.extend_from_slice(&wl_core::audio::packet_to_le_bytes(p));
        });
        offset = end;
    }
    packetizer.flush(|p| out.extend_from_slice(&wl_core::audio::packet_to_le_bytes(p)));

    assert_eq!(out.len(), pcm.len(), "packetizing changed the byte count");
    assert_eq!(out, pcm, "packetizing is not lossless");
}

#[test]
fn the_reference_wav_header_matches_our_writer() {
    let expected = std::fs::read(fixtures().join("pcm/input-1001.wav")).unwrap();
    let pcm = std::fs::read(fixtures().join("pcm/input-1001.pcm")).unwrap();
    let ours = wl_core::wav::wrap_pcm(&pcm);
    assert_eq!(
        &ours[..wl_core::wav::HEADER_LEN],
        &expected[..wl_core::wav::HEADER_LEN],
        "WAV header diverged from the reference"
    );
    assert_eq!(ours.len(), expected.len());
}
