#![allow(dead_code, unused_imports)]

// AUTOGENERATED Components module
pub mod alert_dialog;
pub mod badge;
pub mod button;
pub mod card;
pub mod context_menu;
pub mod dialog;
pub mod input;
pub mod label;
pub mod select;
pub mod separator;
pub mod switch;
pub mod tabs;
pub mod textarea;
pub mod toggle_group;
pub mod tooltip;
