-- Generated by `swift run fixturegen` from tools/fixturegen. Do not hand-edit.
-- Verbatim `sqlite_master.sql` after HistoryStore, DictionaryStore, PolishStore
-- and NotesStore have each run their CREATE TABLE, ordered by object name.

CREATE TABLE dictionary (
    id TEXT PRIMARY KEY,
    phrase TEXT NOT NULL,
    replacement TEXT,
    team_dictionary_id TEXT DEFAULT '00000000-0000-0000-0000-000000000000',
    last_used REAL,
    frequency_used INTEGER DEFAULT 0,
    manual_entry INTEGER DEFAULT 0,
    created_at REAL NOT NULL,
    modified_at REAL NOT NULL,
    is_deleted INTEGER DEFAULT 0,
    source TEXT,
    is_snippet INTEGER DEFAULT 0,
    UNIQUE(phrase, team_dictionary_id)
);

CREATE TABLE notes (
    id TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    content_preview TEXT NOT NULL,
    content TEXT NOT NULL,
    created_at REAL NOT NULL,
    modified_at REAL NOT NULL,
    is_deleted INTEGER DEFAULT 0,
    finalized INTEGER DEFAULT 0
);

CREATE TABLE polish (
    id TEXT PRIMARY KEY,
    initial_text TEXT,
    polished_text TEXT,
    initial_word_count INTEGER,
    polished_word_count INTEGER,
    app TEXT,
    processing_time REAL,
    status TEXT,
    polish_undone INTEGER DEFAULT 0,
    instruction TEXT,
    created_at REAL NOT NULL,
    updated_at REAL NOT NULL
);

-- index sqlite_autoindex_dictionary_1: created implicitly by a PRIMARY KEY or UNIQUE constraint, no DDL

-- index sqlite_autoindex_dictionary_2: created implicitly by a PRIMARY KEY or UNIQUE constraint, no DDL

-- index sqlite_autoindex_notes_1: created implicitly by a PRIMARY KEY or UNIQUE constraint, no DDL

-- index sqlite_autoindex_polish_1: created implicitly by a PRIMARY KEY or UNIQUE constraint, no DDL

-- index sqlite_autoindex_transcripts_1: created implicitly by a PRIMARY KEY or UNIQUE constraint, no DDL

CREATE TABLE transcripts (
    id TEXT PRIMARY KEY,
    asr_text TEXT,
    formatted_text TEXT,
    timestamp REAL,
    app_name TEXT,
    app_bundle_id TEXT,
    duration REAL,
    num_words INTEGER,
    language TEXT
);
